2019-10-23 20:02:46,215 ERROR: Exception on /login [GET] [in /data/data/com.termux/files/usr/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/src/skullquake/pythonsamples/src/flsk_mt_009/app/routes.py", line 82, in login
    return render_template('login.html', title='Sign In', form=form)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/src/skullquake/pythonsamples/src/flsk_mt_009/app/templates/login.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/jinja2/environment.py", line 1005, in render
    return concat(self.root_render_func(self.new_context(vars)))
  File "/home/src/skullquake/pythonsamples/src/flsk_mt_009/app/templates/login.html", line 14, in root
    {{ form.password(size=32,class_="form-control") }}
  File "/home/src/skullquake/pythonsamples/src/flsk_mt_009/app/templates/base.html", line 65, in root
    </li>
  File "/home/src/skullquake/pythonsamples/src/flsk_mt_009/app/templates/login.html", line 25, in block_content
    </form>
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/wtforms/fields/core.py", line 393, in __html__
    return self()
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/wtforms/fields/core.py", line 402, in __call__
    return widgets.HTMLString('<label %s>%s</label>' % (attributes, text or self.text))
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/flask_babel/speaklater.py", line 23, in __str__
    return text_type(self._func(*self._args, **self._kwargs))
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/flask_babel/__init__.py", line 552, in gettext
    t = get_translations()
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/flask_babel/__init__.py", line 227, in get_translations
    [get_locale()],
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/flask_babel/__init__.py", line 257, in get_locale
    rv = babel.locale_selector_func()
  File "/home/src/skullquake/pythonsamples/src/flsk_mt_009/app/__init__.py", line 64, in get_locale
    return request.accept_language.best_match(app.config['LANGUAGES'])
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/werkzeug/local.py", line 348, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'Request' object has no attribute 'accept_language'
2019-10-23 20:03:18,722 INFO: Microblog startup [in /home/src/skullquake/pythonsamples/src/flsk_mt_009/app/__init__.py:61]
2019-10-23 20:06:48,832 INFO: Microblog startup [in /home/src/skullquake/pythonsamples/src/flsk_mt_009/app/__init__.py:61]
2019-10-23 20:13:08,338 INFO: Microblog startup [in /home/src/skullquake/pythonsamples/src/flsk_mt_009/app/__init__.py:61]
2019-10-23 20:28:57,366 INFO: Microblog startup [in /home/src/skullquake/pythonsamples/src/flsk_mt_009/app/__init__.py:61]
2019-10-23 20:33:43,940 INFO: Microblog startup [in /home/src/skullquake/pythonsamples/src/flsk_mt_009/app/__init__.py:61]
